---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webapp-color
  namespace: default
spec:
  selector:
    matchLabels:
      app: simple-webapp-color
  replicas: 2
  template:
    metadata:
      labels:
        app: simple-webapp-color

    spec:
     containers:
     - name: simple-webapp-color
       image: kodekloud/webapp-color
       args: ["--color", "green"]
       ports:
       - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: simple-webapp-color
  namespace: default
  labels:
   app: simple-webapp-color

spec:
 type: NodePort
 selector:
  app: simple-webapp-color
 ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30000
